name = "todo"
compatibility_date = "2024-01-17"

[[d1_databases]]
binding = "DB"                     # i.e. available in your Worker on env.DB
database_name = "todo"
database_id = ""
preview_database_id = "local-todo"
